### ISSUE TITLE
Building sphinx-relay in Docker - 500,000 $@

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-stack#1]
- Building relay in Docker is running across dependecy issues
- in sphinx-relay: `docker build --no-cache -t sphinx-relay .`
- Current error: `ERR! enoent undefined ls-remote -h -t https://github.com/tierion/js-macaroon.git`
- https://github.com/stakwork/sphinx-relay/blob/master/Dockerfile

- We want to run the full stack with latest relay included 
- https://github.com/stakwork/sphinx-stack/blob/master/docker-compose.yml
- you can use your locally built relay image for `alice`, `bob`, and `carol`

- And run the tests
- https://github.com/stakwork/sphinx-relay/tree/master/src/tests
- After running the sphinx-stack, copy the `sphinx-stack/relay/NODES.json` to `sphinx-relay/src/tests/configs/nodes.json` 
- `npx ava src/tests/controllers/self.test.ts --verbose --serial --timeout=2m`

**Comment by kevkevinpal** [comment]
PR that may resolve this issue 

https://github.com/stakwork/sphinx-relay/pull/232
