### ISSUE TITLE
Update logging to have shorter timestamp - $@ 10,000

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-stack#16]
Bounty for 10,000 sats

This is a pretty simple change but will be good for anyone trying to learn the sphinx-stack and dev environment.

We recently updated our logging to include timestamps and other data for every log, but the timestamp is a bit too long and takes too much space

------

What it currently looks like
`Mon, 24 Jan 2022 18:05:40 GMT`

We can try making this shorter to maybe look something like this
`01-24-22T18:05:40`
but feel free to include other ideas

-----

the file you will want to make your changes in is 
`./sphinx-relay/src/util/logger`
or just click here
https://github.com/stakwork/sphinx-relay/blob/master/src/utils/logger.ts#L59

----

For this bounty, you probably want to get `sphinx-stack` running and then running `docker logs alice.sphinx` to check if your changes look good

feel free to DM me, post questions on the developing on sphinx tribe or right here and I can point you in the right direction

**Comment by Rassl** [comment]
https://github.com/stakwork/sphinx-relay/pull/280

**Comment by kevkevinpal** [comment]
@Rassl thanks for the work if you're ever looking to cash in the 10,000 sats please reach out
