### ISSUE TITLE
full stack testing - 250,000 $@

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-stack#2]
We need a full test suite for the whole sphinx stack! We have started building it out here: https://github.com/stakwork/sphinx-relay/tree/master/src/tests. These tests run against a local `sphinx-stack` setup. After getting `sphinx-stack` up and running:
 - replace `sphinx-relay/tree/master/src/tests/configs/nodes.json` with your own file from `sphinx-stack/relay/NODES.json`
 - in `sphinx-relay` run the "contact" test with `npx ava src/tests/controllers/contacts.test.ts --verbose --serial --timeout=2m`
 - This tests one of the most important parts of Sphinx: the key exchange that ensures all messages are end-to-end encrypted!
 - try changing the test to work with alice + carol instead of alice + bob. https://github.com/stakwork/sphinx-relay/blob/master/src/tests/controllers/contacts.test.ts#L25 (`checkContact(t, nodes[0], nodes[2])`). For me it does not work with alice + carol! 
 - This *should* work every time. For me it is intermittent
 - Please respond to this issue with your findings

**Comment by kevkevinpal** [comment]
I think I found where the issue was, I'm pretty sure it was in getContacts test. I just made updates in this PR

https://github.com/stakwork/sphinx-relay/pull/233

**Comment by Evanfeenstra** [comment]
sweet, thanks @kevkevinpal !
