### ISSUE TITLE
Batching MQTT messages in sphinx-tribes - $@ 650,000

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-stack#21]
`[Description]`
Right now encrypted MQTT messages are individually sent from tribe admin's node to the MQTT broker, where they are propagated to the recipients. As tribes grow larger, this will become a bottleneck. Instead, there should be a POST endpoint that receives a batch of messages, and sends them over MQTT (and sets the "activity" in the tribe)

`[Complexity] (1,2,3,5,8)`
3

`[Acceptance Criteria] (Given, When, Then)`
All existing tests in `sphinx-stack` passing, but without relay sending the messages individually.

Tribes server should have a new route, which accepts the batch, and also connects to sphinx-mqtt to send them off. Tribes server will need an mqtt "client" using this lib github.com/eclipse/paho.mqtt.golang

In relay https://github.com/stakwork/sphinx-relay/blob/master/src/network/send.ts, instead of each message being sent individually, they should be signed and collected, then sent as a batch call to tribes server.

**Comment by kevkevinpal** [comment]
I'm trying to understand where in relay in https://github.com/stakwork/sphinx-relay/blob/master/src/network/send.ts are we sending each message individually? Is there somewhere we are looping through each person in the tribe to send the mqtt message if we are the tribe owner?

**Comment by Evanfeenstra** [comment]
Yup on this line the loop starts https://github.com/stakwork/sphinx-relay/blob/master/src/network/send.ts#L127

And finally sent on this line https://github.com/stakwork/sphinx-relay/blob/master/src/network/send.ts#L179

**Comment by Lombitron** [comment]
OK, if I understand this correctly, there are two parts to this change.

1) **sphinx-relay** currently `signAndSend()` for "the message" to each recipient. that gets published to MQTT from **sphinx-relay**. So, this needs to be changed to sign each message, batch it up into a new JSON object, then send that to the new endpoint in **sphinx-tribes** (see point 2.)

2) **sphinx-tribes**  needs a new API endpoint adding to deserialise this new object to a collection of signed messages, then using the MQTT client specified above, send each of these messages to MQTT.

**Comment by Evanfeenstra** [comment]
exactly @Lombitron, definitely start on the Golang side :) as that more of an "addition" and doesnt really modify any existing code, just adds new features

**Comment by Lombitron** [comment]
Would you please create a branch on `sphinx-tribes` so that I can make a PR?

**Comment by kevkevinpal** [comment]
> Would you please create a branch on `sphinx-tribes` so that I can make a PR?

Instead of us making a new branch, create a new branch on your fork of the repo and then you can open a PR from there to our repo

Let me know if that makes sense

**Comment by Lombitron** [comment]
done - stakwork/sphinx-tribes/pull/176

**Comment by Lombitron** [comment]
created a PR for the `sphinx-relay` changes stakwork/sphinx-relay/pull/306 
Not completed yet - but I would appreciate a 2nd set of eyes before I go much further

**Comment by Evanfeenstra** [comment]
@Lombitron great job on the Golang side of this issue!
