### ISSUE TITLE
chat invoices test - $@ 125,000

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-stack#8]
- Here we have a "chat invoices test", written in plain JS against a different testing setup: 
https://github.com/stakwork/sphinx-win-linux-desktop/blob/master/test-ava/tests/test-09-chatInvoice.js
- but we want to run this against the `sphinx-stack`
- and migrate it to typescript here https://github.com/stakwork/sphinx-relay/tree/master/src/tests
- write a test where node 1 and node 2 connect and exchange contact keys. Then node 1 sends an invoice message to node 2. Node 2 pays the lightning invoice. Verify both channel balances are correct at the end.

Here is a video with some tips for setting up the `sphinx-stack`: https://www.loom.com/share/46fc47f208194317a78048d2e12b9c09

After running the `sphinx-stack`, you can copy the contents of `relay/NODES.json` into `sphinx-relay/src/testing/configs/nodes.json` to the relay tests against your local `sphinx-stack`

**Comment by kevkevinpal** [comment]
Closing this issue as it was finished in this PR https://github.com/stakwork/sphinx-relay/pull/250
